# Generated by Django 2.2.1 on 2019-05-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('pay_type', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Creator')),
            ],
            options={
                'db_table': 'recruit_post',
            },
        ),
        migrations.CreateModel(
            name='RecruitQnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('recruit_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.RecruitPost')),
            ],
            options={
                'db_table': 'recruit_qna',
            },
        ),
        migrations.CreateModel(
            name='RecruitProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('resume_title', models.CharField(max_length=100)),
                ('resume_contents', models.TextField()),
                ('resume_file', models.CharField(max_length=255)),
                ('resume_confirm', models.BooleanField(default=False)),
                ('resume_result', models.CharField(max_length=50)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Editor')),
                ('recruit_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.RecruitPost')),
            ],
            options={
                'db_table': 'recruit_process',
            },
        ),
    ]
